In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('.ipynb_checkpoints/2022-23/playerData.csv')
X = dataset.iloc[:, [5] + list(range(8,22)) ]
y = dataset.iloc[:, 35]  # Target variable
y = y.values.reshape(-1,1)
print(y)

[[ 0]
 [52]
 [ 0]
 ...
 [ 0]
 [66]
 [ 0]]


In [4]:
#from sklearn.preprocessing import StandardScaler
#sc_X = StandardScaler()
#sc_y = StandardScaler()
#X = sc_X.fit_transform(X)
#y = sc_y.fit_transform(y)

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.linear_model import Ridge
ml_model = Ridge(alpha=1.0)
ml_model.fit(X_train,y_train)

Ridge()

In [7]:
from sklearn.linear_model import Lasso
ml_model = Lasso(alpha=1.0)
ml_model.fit(X_train,y_train)

Lasso()

In [8]:
#desicion tree
from sklearn import tree
ml_model = tree.DecisionTreeRegressor()
ml_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [9]:
#random forest
from sklearn.ensemble import RandomForestRegressor
ml_model = RandomForestRegressor(max_depth=10,random_state=00)
ml_model.fit(X_train,y_train)

c:\Python311\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(max_depth=10, random_state=0)

In [10]:
#nearest neighbour
from sklearn.neighbors import KNeighborsRegressor
ml_model = KNeighborsRegressor(n_neighbors=10)
ml_model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=10)

In [11]:
#support vector machine
from sklearn.svm import SVR
ml_model = SVR(kernel = 'rbf')
ml_model.fit(X_train, y_train)

c:\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [12]:
#linear regression
from sklearn.linear_model import LinearRegression
ml_model = LinearRegression()
ml_model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred = ml_model.predict(X_test)
display(y_pred)
display(y_test)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

array([[ 1.72428486e+01],
       [ 8.06882005e+00],
       [ 4.50211028e+01],
       [ 9.52706227e+00],
       [ 1.32098900e+01],
       [ 2.36940391e+01],
       [ 1.73334897e+01],
       [ 4.70748643e-01],
       [ 4.79549892e+01],
       [ 1.66636285e+01],
       [ 2.82730195e+01],
       [ 5.70744022e-01],
       [ 8.59868461e+00],
       [ 1.26038678e+01],
       [ 2.57772378e+01],
       [ 3.12879021e+01],
       [ 7.68982815e+00],
       [ 2.26841923e+01],
       [-3.17107354e+00],
       [ 7.23814895e+00],
       [-3.55496355e+00],
       [ 1.55098078e+01],
       [ 2.57453541e+01],
       [ 1.23814403e+01],
       [ 8.42143177e+00],
       [-1.33502095e+00],
       [ 3.18326634e+01],
       [ 5.80819446e+00],
       [ 1.31043109e+01],
       [ 2.04150568e+01],
       [ 1.14102607e+00],
       [ 2.98112680e+01],
       [ 2.10143186e+01],
       [ 3.15711507e+01],
       [ 1.61001773e+01],
       [-1.73387581e+00],
       [ 1.77575024e+01],
       [ 2.77938065e+00],
       [ 3.8

array([[ 22],
       [  0],
       [ 72],
       [  0],
       [  0],
       [ 40],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  4],
       [  0],
       [ 28],
       [  0],
       [ 43],
       [  0],
       [  0],
       [  0],
       [  3],
       [  0],
       [  0],
       [  0],
       [ 27],
       [  0],
       [  0],
       [127],
       [  0],
       [ 10],
       [  0],
       [ 10],
       [  0],
       [ 88],
       [ 30],
       [ 16],
       [  0],
       [  0],
       [  0],
       [  0],
       [  4],
       [ 77],
       [  0],
       [  0],
       [ 24],
       [ 14],
       [ 92],
       [ 40],
       [ 17],
       [103],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  9],
       [  0],
       [  0],
       [118],
       [  0],
       [ 32],
       [  0],
       [  0],
       [  0],
       [  0],
       [  7],
       [ 98],
       [  0],
       [234],
       [  5],
       [ 26],
       [  0],
      

Mean Absolute Error: 22.329794030070417


In [14]:

plt.scatter(y_test, y_pred)
plt.xlabel('Reality')
plt.ylabel('Prediction')
p1 = max(max(y_pred), max(y_pred))
p2 = min(min(y_pred), min(y_pred))
plt.plot([p1, p2], [p1, p2], 'b-')
plt.title('Actual vs Predicted time out Width')
plt.show()

In [15]:
new_dataset = pd.read_csv('.ipynb_checkpoints/2022-23/yearly_data_above_zero.csv')
new_X = new_dataset.iloc[:, [5] + list(range(8,22)) ]
new_y = new_dataset.iloc[:, 35]  # Target variable
new_y = new_y.values.reshape(-1,1)
new_y_pred = ml_model.predict(new_X)
print(new_y)
print(new_y_pred)

mae = mean_absolute_error(new_y,new_y_pred)
print("Mean Absolute Error:", mae)

[[151]
 [ 49]
 [264]
 [ 42]
 [ 50]
 [ 11]
 [111]
 [ 54]
 [248]
 [ 72]
 [155]
 [ 51]
 [103]
 [136]
 [ 11]
 [104]
 [127]
 [107]
 [ 38]
 [ 12]
 [ 96]
 [  9]
 [  9]
 [ 68]
 [ 27]
 [ 78]
 [237]
 [ 57]
 [234]
 [ 23]
 [232]
 [226]
 [ 58]
 [ 72]
 [  5]
 [ 60]
 [ 62]
 [ 99]
 [ 49]
 [  5]
 [225]
 [225]
 [ 22]
 [ 57]
 [ 35]
 [ 23]
 [ 92]
 [ 12]
 [217]
 [ 70]
 [ 50]
 [ 77]
 [ 68]
 [ 30]
 [215]
 [214]
 [ 62]
 [  4]
 [ 30]
 [ 75]
 [ 20]
 [ 39]
 [ 10]
 [260]
 [ 36]
 [210]
 [ 18]
 [ 39]
 [  2]
 [ 37]
 [ 23]
 [ 24]
 [ 74]
 [  9]
 [ 64]
 [ 31]
 [ 37]
 [ 55]
 [ 76]
 [ 16]
 [191]
 [ 63]
 [ 26]
 [ 16]
 [ 44]
 [ 87]
 [189]
 [ 40]
 [ 41]
 [ 44]
 [ 32]
 [ 22]
 [ 57]
 [183]
 [ 39]
 [ 21]
 [ 20]
 [177]
 [ 26]
 [118]
 [ 69]
 [ 63]
 [  5]
 [ 28]
 [ 12]
 [ 13]
 [ 31]
 [  4]
 [ 28]
 [ 32]
 [  9]
 [ 40]
 [  2]
 [ 41]
 [ 22]
 [  1]
 [ 25]
 [165]
 [ 11]
 [ 22]
 [ 56]
 [ 19]
 [ 43]
 [ 45]
 [ 20]
 [ 20]
 [ 72]
 [ 47]
 [  2]
 [  2]
 [ 50]
 [ 12]
 [  7]
 [ 26]
 [147]
 [  7]
 [ 34]
 [  8]
 [ 40]
 [  7]
 [ 14]
 [ 14]
 [ 26]